# Generated by Django 5.1.1 on 2024-11-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=models.CharField(blank=True, default='http://127.0.0.1:9000/meatfish/default.jpg'),
        ),
    ]
