# Generated by Django 5.1.1 on 2024-10-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner',
            name='qr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
