# Generated by Django 5.1.1 on 2024-10-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_dish_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner',
            name='total_cost',
            field=models.IntegerField(default=0),
        ),
    ]
